-- 2022.7.16
-- create database
CREATE DATABASE `horizon` DEFAULT CHARACTER SET utf8mb4;
USE horizon;
-- insert admin user
INSERT INTO users(id, user_name, `nick_name`, `password`, `phone`, `status`, created_at, updated_at)
VALUES('1', 'admin', '管理员', '$2a$10$kfcWYvoUMzY7BtQw/IrMd.aVilOs6.b/xbt560dqR467qz28TpL8K', '', 'Enabled', NOW(), NOW());
-- insert role
INSERT INTO `roles`(`id`, `name`, `describe`)VALUES('admin', '系统管理员', '');
-- insert admin user role
INSERT INTO `user_roles`(`user_id`, `role_id`)VALUES('1', 'admin');
-- insert inspection metrics
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('BACKUP_STATUS','备份状态','正常/异常',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('BIGTABLE_NUM','大表数量','个',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('CPU_UTILIZATION','CPU使用率','%',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('DEADLOCK','死锁','次',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('DISK_UTILIZATION','磁盘使用率','%',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('HA_STATUS','HA状态','开/关',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('HIGH_RISK_ACCOUNT','高危账号', '个', now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('IBP_CACHE_HITS_RATE','缓存命中率','%',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('INCREMENT_ID_OVERFLOW','自增主键溢出','个',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('IOPS_UTILIZATION','IOPS使用率','%',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('LOCK_WAIT','锁等待','次',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('MEMORY_UTILIZATION','内存使用率','%',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('NETWORK_TRAFFIC_IN','网络流量in','bytes',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('NETWORK_TRAFFIC_OUT','网络流量out','bytes',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('QPS','请求数','个/秒',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('REPLICATION_DELAY','复制延迟','秒',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('REPLICATION_STATUS','复制状态','正常/异常',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('SLOW_SQL_NUM','慢SQL数量','个',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('SWAP_USE','SWAP使用量','MB',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('THREADS_CONNECTED','连接数使用率','%',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('THREADS_RUNNING_NUM','并发线程数','个',now(),now());
INSERT INTO `metrics` (`key`,`name`,`unit`,`created_at`,`updated_at`) VALUES ('TPS','事务数','个/秒',now(),now());
-- insert menus
INSERT INTO `menus` (`id`,`name`,`parent_id`,`meta`,`component`,`redirect`,`path`,`action_data`,`action_list`,`created_at`,`updated_at`) VALUES (1,'Instance',0,'{\"icon\": \"table\", \"show\": true, \"title\": \"menu.instance\"}','RouteView','/instance/list',NULL,'[]','[]',now(),now());
INSERT INTO `menus` (`id`,`name`,`parent_id`,`meta`,`component`,`redirect`,`path`,`action_data`,`action_list`,`created_at`,`updated_at`) VALUES (2,'System',0,'{\"icon\": \"table\", \"show\": true, \"title\": \"menu.system\"}','RouteView','/system/user',NULL,'[]','[]',now(),now());
INSERT INTO `menus` (`id`,`name`,`parent_id`,`meta`,`component`,`redirect`,`path`,`action_data`,`action_list`,`created_at`,`updated_at`) VALUES (3,'SQLAudit',0,'{\"icon\": \"table\", \"show\": true, \"title\": \"menu.sqlaudit\"}','RouteView','/sqlaudit/project',NULL,'[]','[]',now(),now());
INSERT INTO `menus` (`id`,`name`,`parent_id`,`meta`,`component`,`redirect`,`path`,`action_data`,`action_list`,`created_at`,`updated_at`) VALUES (1001,'InstanceList',1,'{\"icon\": \"table\", \"show\": true, \"title\": \"menu.instance.list\"}','InstanceList',NULL,'/instance/list','[{\"url\": \"/instance/add\", \"action\": \"add\", \"describe\": \"新增\", \"defaultCheck\": false}, {\"url\": \"/instance/:instId\", \"action\": \"get\", \"describe\": \"详情\", \"defaultCheck\": false}, {\"url\": \"/instance/query\", \"action\": \"query\", \"describe\": \"查询\", \"defaultCheck\": false}, {\"url\": \"/instance/edit\", \"action\": \"edit\", \"describe\": \"修改\", \"defaultCheck\": false}, {\"url\": \"/instance/delete\", \"action\": \"delete\", \"describe\": \"删除\", \"defaultCheck\": false}, {\"url\": \"/instance/db/:instId\", \"action\": \"getDbs\", \"describe\": \"获取数据库列表\", \"defaultCheck\": false}]','[\"add\", \"query\", \"edit\", \"delete\"]',now(),now());
INSERT INTO `menus` (`id`,`name`,`parent_id`,`meta`,`component`,`redirect`,`path`,`action_data`,`action_list`,`created_at`,`updated_at`) VALUES (1002,'InstanceInspection',1,'{\"icon\": \"table\", \"show\": true, \"title\": \"menu.instance.inspection\"}','InstanceInspection',NULL,'/instance/inspection','[{\"url\": \"/inspection/:id\", \"action\": \"get\", \"describe\": \"详情\", \"defaultCheck\": false}, {\"url\": \"/inspection/query\", \"action\": \"query\", \"describe\": \"查询\", \"defaultCheck\": false}, {\"url\": \"/score\", \"action\": \"query\", \"describe\": \"查询\", \"defaultCheck\": false}]','[\"get\", \"query\"]',now(),now());
INSERT INTO `menus` (`id`,`name`,`parent_id`,`meta`,`component`,`redirect`,`path`,`action_data`,`action_list`,`created_at`,`updated_at`) VALUES (2001,'SystemUser',2,'{\"icon\": \"table\", \"show\": true, \"title\": \"menu.system.user\"}','SystemUser',NULL,'/system/user','[{\"url\": \"/user/add\", \"action\": \"add\", \"describe\": \"新增\", \"defaultCheck\": false}, {\"url\": \"/user/info\", \"action\": \"get\", \"describe\": \"详情\", \"defaultCheck\": false}, {\"url\": \"/user/nav\", \"action\": \"getNav\", \"describe\": \"获取菜单\", \"defaultCheck\": false}, {\"url\": \"/user/query\", \"action\": \"query\", \"describe\": \"查询\", \"defaultCheck\": false}, {\"url\": \"/user/edit\", \"action\": \"edit\", \"describe\": \"修改\", \"defaultCheck\": false}, {\"url\": \"/user/delete\", \"action\": \"delete\", \"describe\": \"删除\", \"defaultCheck\": false}, {\"url\": \"/user/resetPassword\", \"action\": \"resetPassword\", \"describe\": \"重置密码\", \"defaultCheck\": false}]','[\"add\", \"query\", \"edit\", \"delete\", \"resetPassword\"]',now(),now());
INSERT INTO `menus` (`id`,`name`,`parent_id`,`meta`,`component`,`redirect`,`path`,`action_data`,`action_list`,`created_at`,`updated_at`) VALUES (2002,'SystemRole',2,'{\"icon\": \"table\", \"show\": true, \"title\": \"menu.system.role\"}','SystemRole',NULL,'/system/role','[{\"url\": \"/menu\", \"action\": \"add\", \"describe\": \"查询菜单\", \"defaultCheck\": false}, {\"url\": \"/role/add\", \"action\": \"add\", \"describe\": \"新增\", \"defaultCheck\": false}, {\"url\": \"/role/query\", \"action\": \"query\", \"describe\": \"查询\", \"defaultCheck\": false}, {\"url\": \"/role/edit\", \"action\": \"edit\", \"describe\": \"修改\", \"defaultCheck\": false}, {\"url\": \"/role/delete/:id\", \"action\": \"delete\", \"describe\": \"删除\", \"defaultCheck\": false}, {\"url\": \"/role/permission\", \"action\": \"funcPerms\", \"describe\": \"功能权限\", \"defaultCheck\": false}]','[\"add\", \"query\", \"edit\", \"delete\", \"funcPerms\"]',now(),now());
INSERT INTO `menus` (`id`,`name`,`parent_id`,`meta`,`component`,`redirect`,`path`,`action_data`,`action_list`,`created_at`,`updated_at`) VALUES (3001,'SQLAuditProject',3,'{\"icon\": \"table\", \"show\": true, \"title\": \"menu.sqlaudit.project\"}','SQLAuditProject',NULL,'/sqlaudit/project','[{\"url\": \"/sqlaudit/project/add\", \"action\": \"add\", \"describe\": \"新增\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/project\", \"action\": \"query\", \"describe\": \"查询\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/project/edit\", \"action\": \"edit\", \"describe\": \"修改\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/project/delete/:id\", \"action\": \"delete\", \"describe\": \"删除\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/project/:projId\", \"action\": \"get\", \"describe\": \"详情\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/project/resource/config\", \"action\": \"config\", \"describe\": \"权限配置\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/project/role\", \"action\": \"getRole\", \"describe\": \"查询项目角色\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/project/user/:userName\", \"action\": \"getUser\", \"describe\": \"查询用户项目\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/project/datasource/:projId\", \"action\": \"getDatasource\", \"describe\": \"查询项目数据源\", \"defaultCheck\": false}]','[\"add\", \"query\", \"edit\", \"delete\"]',now(),now());
INSERT INTO `menus` (`id`,`name`,`parent_id`,`meta`,`component`,`redirect`,`path`,`action_data`,`action_list`,`created_at`,`updated_at`) VALUES (3002,'SQLAuditWorkflow',3,'{\"icon\": \"table\", \"show\": true, \"title\": \"menu.sqlaudit.workflow\", \"hideChildren\": true}','RouteView','/sqlaudit/workflow','','[{\"url\": \"/sqlaudit/workflow/add\", \"action\": \"add\", \"describe\": \"新增\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflow\", \"action\": \"query\", \"describe\": \"查询\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflow/edit\", \"action\": \"edit\", \"describe\": \"修改\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflow/:id\", \"action\": \"delete\", \"describe\": \"删除\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflow/progress/:id\", \"action\": \"progress\", \"describe\": \"获取进度\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflow/audit\", \"action\": \"audit\", \"describe\": \"审核\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflow/cancel\", \"action\": \"cancel\", \"describe\": \"取消\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflow/execute\", \"action\": \"execute\", \"describe\": \"执行\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflow/scheduledExecute\", \"action\": \"scheduledExecute\", \"describe\": \"定时执行\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflow/sqlDetail\", \"action\": \"delete\", \"describe\": \"sql详情\", \"defaultCheck\": false}]','[\"add\", \"query\", \"edit\", \"delete\"]',now(),now());
INSERT INTO `menus` (`id`,`name`,`parent_id`,`meta`,`component`,`redirect`,`path`,`action_data`,`action_list`,`created_at`,`updated_at`) VALUES (3003,'SQLAuditWorkflowTemplate',3,'{\"icon\": \"table\", \"show\": true, \"title\": \"menu.sqlaudit.workflowTemplate\"}','SQLAuditWorkflowTemplate',NULL,'/sqlaudit/workflowTemplate','[{\"url\": \"/sqlaudit/workflowTemplate/add\", \"action\": \"add\", \"describe\": \"新增\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflowTemplate\", \"action\": \"query\", \"describe\": \"查询\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflowTemplate/edit\", \"action\": \"edit\", \"describe\": \"修改\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflowTemplate/:id\", \"action\": \"delete\", \"describe\": \"删除\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflowTemplate/config\", \"action\": \"config\", \"describe\": \"配置\", \"defaultCheck\": false}]','[\"add\", \"query\", \"edit\", \"delete\"]',now(),now());
INSERT INTO `menus` (`id`,`name`,`parent_id`,`meta`,`component`,`redirect`,`path`,`action_data`,`action_list`,`created_at`,`updated_at`) VALUES (3002001,'SQLAuditWorkflowList',3002,'{\"icon\": \"table\", \"show\": false, \"title\": \"menu.sqlaudit.workflow.list\"}','SQLAuditWorkflow',NULL,'/sqlaudit/workflow','[{\"url\": \"/sqlaudit/workflow/add\", \"action\": \"add\", \"describe\": \"新增\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflow\", \"action\": \"query\", \"describe\": \"查询\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflow/edit\", \"action\": \"edit\", \"describe\": \"修改\", \"defaultCheck\": false}, {\"url\": \"/sqlaudit/workflow/:id\", \"action\": \"delete\", \"describe\": \"删除\", \"defaultCheck\": false}]','[\"add\", \"query\", \"edit\", \"delete\"]',now(),now());
INSERT INTO `menus` (`id`,`name`,`parent_id`,`meta`,`component`,`redirect`,`path`,`action_data`,`action_list`,`created_at`,`updated_at`) VALUES (3002002,'SQLAuditWorkflowDetail',3002,'{\"icon\": \"table\", \"show\": false, \"title\": \"menu.sqlaudit.workflow.detail\"}','SQLAuditWorkflowDetail',NULL,'/sqlaudit/workflowDetail/:workflowId','[{\"action\": \"add\", \"describe\": \"新增\", \"defaultCheck\": false}, {\"action\": \"query\", \"describe\": \"查询\", \"defaultCheck\": false}, {\"action\": \"edit\", \"describe\": \"修改\", \"defaultCheck\": false}, {\"action\": \"delete\", \"describe\": \"删除\", \"defaultCheck\": false}]','[\"add\", \"query\", \"edit\", \"delete\"]',now(),now());

-- insert admin role permissions (ALL menu)
INSERT IGNORE INTO role_permissions(role_id, menu_id, action_data, action_list)
SELECT 'admin' AS role_id, id AS menu_id, action_data, action_list FROM menus;

-- insert sql audit project role
INSERT IGNORE INTO `project_roles` (`id`, `name`, `describe`) VALUES ('proj_admin', '负责人', '');
INSERT IGNORE INTO `project_roles` (`id`, `name`, `describe`) VALUES ('proj_dba', 'DBA', '');
INSERT IGNORE INTO `project_roles` (`id`, `name`, `describe`) VALUES ('proj_developer', '开发', '');
INSERT IGNORE INTO `project_roles` (`id`, `name`, `describe`) VALUES ('proj_tester', '测试', '');